# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  test:
    cmds:
      - go test
  clean:
    cmds:
      - rm -f ./bin/dover
  build:dev:
    cmds:
      - task: clean
      - go build -o bin/dover
  build:release:
    - go build -o release/dover
