# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test ./app
  test:cov:
    cmds:
      - go test -coverprofile=coverage.out ./app
      - go tool cover -html=coverage.out
  clean:
    cmds:
      - rm -f ./bin/dover-mac
      - rm -f ./bin/dover.exe
  build:dev:
    cmds:
      - task: clean
      - go build -o bin/dover-mac
      - GOOS=windows go build -o bin/dover.exe
  build:release:
    cmds:
      - go build -o bin/dover
      - GOOS=windows go build -o bin/dover.exe
