# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test
  clean:
    cmds:
      - rm -f ./bin/dover-mac
      - rm -f ./bin/dover.exe
  build:dev:-mac
    cmds:
      - task: clean
      - go build -o bin/dover-mac
      - GOOS=windows go build -o bin/dover.exe
  build:release:
    cmds:
      - go build -o bin/dover
      - GOOS=windows go build -o bin/dover.exe
